name: thingsboard
docker:
  release:
    image: "thingsboard/tb-postgres:3.4.0"
  ports:
    - port: 8080
      protocol: tcp
    - port: 1883
      protocol: tcp
    - port: 7070
      protocol: tcp
    - port: 5683-5688
      protocol: udp
  volumes:
    - name: mytb-data
      mountPath: /data
    - name: mytb-logs
      mountPath: /var/log/thingsboard
